name: flutter_templates_anabebe
description: A template for implementing various Flutter widgets and other features.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.16.2 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  anabebe_packages:
    git:
      url: https://github.com/anabebe1020/anabebe_packages.git
      ref: master
  cupertino_icons: ^1.0.2
  flutter_riverpod: ^1.0.3
  google_fonts: ^2.3.1
  badges: ^2.0.2
  flutter_native_splash: ^2.0.4
  go_router: ^3.0.7

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_launcher_icons: ^0.9.2
  flutter_lints: ^1.0.0

flutter:
  uses-material-design: true

flutter_icons:
  image_path: "assets/icon/launcher.png"
  android: true
  ios: true

flutter_native_splash:
  image: "assets/icon/launcher.png"
  color: "696969"